### PR TITLE
Feat: Multiple mindmaps in multiple tabs

### PR DESCRIPTION
**Pull request by james-tindal**
Addresses #85.

The functionality is there but there are two main issues.
Opening a new map always splits the screen again instead of adding a tab to the split that's already there.
When you reload Obsidian, the mindmap tabs are empty (except in single-tab unpinned mode).
There is an option to switch between single tab and multiple tab mode.

I will add documentation too.

### CODE REVIEW

**Comment by AdrianSimionov** [comment]
Please do not merge while the mentioned issues remain unresolved, as are not very user friendly. Is it possible to solve the issues you mentioned?

**Comment by james-tindal** [comment]
It's definitely solvable. Just an area of the Obsidian plugin system that's not super well documented, so it's taking a while.

**Comment by james-tindal** [comment]
Progress on this is: I've got it to stop opening new splits every time, but this causes a weird bug in d3-zoom that makes the maps freeze for a second or two when they load. @AdrianSimionov

**Comment by james-tindal** [comment]
Fixed that problem. Now to get the right files to load on startup.

**Pull request merged**
